# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='crawl_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Task_ID', models.IntegerField()),
                ('crawl_domain', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('decode', models.CharField(max_length=255)),
                ('date_time', models.DateTimeField()),
            ],
        ),
    ]
